Repository PowerShell/PowerShell-RFC, pull requests merged in 2020-03, with the labels that each got.

#127 RFC for String Manipulating Cmdlets
  X-Withdrawn/RFC0054-String-Manipulating-Cmdlets.md
Labels: Review - Waiting on Author

#137 Submitting ConvertFrom-Html RFC
  X-Rejected/RFC0055-ConvertFrom-Html.md
Labels: Review - Committee

#153 PowerShell in Applications Mode
  X-Withdrawn/RFC0056-PowerShell-in-Application-Mode.md
Labels: Review - Waiting on Author

#203 Cross-Platform-OutGridView
  X-Withdrawn/RFC0057-Cross-Platform-Out-GridView.md
  assets/Out-GridView/out_gridview_mockup.png
Labels: Review - Committee, Review - Open for Comments
